# -*- coding: utf-8 -*-
"""Tracknet Tennis Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xx4jc15wOgGvsm_9-_o7-xg-gBvmYbz0

# Tracknet Tennis  ball detection

Video Dimension and Resizing
"""

## Connect google colab to google drive to share data between the two
from google.colab import drive
drive.mount('/content/drive')

import imageio.v3 as iio
import cv2
# Import Tennis video which model will track.
video = cv2.VideoCapture('/content/drive/MyDrive/Tennis/clay_04.mp4')
print('fps:', int(video.get(cv2.CAP_PROP_FPS)))
print('shape: (',int(video.get(cv2.CAP_PROP_FRAME_COUNT)),',',int(video.get(cv2.CAP_PROP_FRAME_HEIGHT)),',',
      int(video.get(cv2.CAP_PROP_FRAME_WIDTH)),', 3 )')

# Load the video
import moviepy.editor as mp

video = mp.VideoFileClip('/content/drive/MyDrive/Tennis/clay_04.mp4')

# Resize the video
resized_video = video.resize((1280,720))

# Save the resized video
resized_video.write_videofile("/content/drive/MyDrive/Tennis/clay_004.mp4")

"""## TrackNet: Ball Detection"""

# Copy TrackNet package to colab
!git clone https://github.com/yastrebksv/TrackNet.git

# Commented out IPython magic to ensure Python compatibility.
# Change working directory to TrackNet folder
# Install TrackNet package requirements
# %cd /content/TrackNet
!pip install -r requirements.txt

## TrackNet: Ball Detection
# --model_path= PATH_TO_TRAINED_BALL_DETECTION_MODEL
# --video_path= PATH_TO_INPUT_VIDEO_FILE
# --video_out_path= PATH_TO_OUTPUT_VIDEO_FILE
!python infer_on_video.py --model_path=/content/drive/MyDrive/Tennis/tracknet_ball_model.pt --video_path=/content/drive/MyDrive/Tennis/clay_004.mp4 --video_out_path="/content/drive/MyDrive/Tennis/clay_0004.mp4"

"""## TrackNet: Court Detection"""

# Copy TrackNet package to colab
!git clone https://github.com/yastrebksv/TennisCourtDetector.git

# Commented out IPython magic to ensure Python compatibility.
# Change working directory to TrackNet folder
# Install TrackNet package requirements
# %cd /content/TennisCourtDetector
!pip install -r requirements.txt

## TrackNet: Court Detection
# --model_path= PATH_TO_TRAINED_BALL_DETECTION_MODEL
# --input_path= PATH_TO_INPUT_VIDEO_FILE
# --output_path= PATH_TO_OUTPUT_VIDEO_FILE
!python infer_in_video.py --model_path=/content/drive/MyDrive/Tennis/tracknet_court_model.pt --input_path=/content/drive/MyDrive/Tennis/clay_004.mp4 --output_path="/content/drive/MyDrive/Tennis/court_clay_004.mp4"

"""## TrackNet: Ball, Court, Bounce Detection"""

# Copy TrackNet package to colab
!git clone https://github.com/yastrebksv/TennisProject.git

# Commented out IPython magic to ensure Python compatibility.
# Change working directory to TrackNet folder
# Install TrackNet package requirements
# %cd /content/TennisProject
!pip install -r requirements.txt

!pip3 install catboost

!pip install scenedetect[opencv] --upgrade

# TrackNet: Ball, Bounce, Court Detection:
# --path_ball_track= PATH_TO_TRAINED_BALL_DETECTION_MODEL
# --path_court_model= PATH_TO_TRAINED_COURT_DETECTION_MODEL
# --path_bounce_model= PATH_TO_TRAINED_BOUNCE_DETECTION_MODEL
# --path_input_video= PATH_TO_INPUT_VIDEO_FILE
# --path_output_video= PATH_TO_OUTPUT_VIDEO_FILE
!pip install tensorboardX
!python infer_on_video.py --path_ball_track_model=/content/drive/MyDrive/Tennis/tracknet_ball_model.pt --path_court_model=/content/drive/MyDrive/Tennis/tracknet_court_model.pt  --path_bounce_model=/content/drive/MyDrive/Tennis/tracknet_bounce_model.cbm --path_input_video="/content/drive/MyDrive/Tennis/clay_004.mp4" --path_output_video="/content/drive/MyDrive/Tennis/final_clay_004.mp4"